services:
  - type: worker
    name: bitunix-scanner-bot
    runtime: node
    plan: starter
    region: singapore
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: INTERVAL_MIN
        value: "10"
      - key: PROXY_URL
        sync: false
