services:
  - type: worker
    name: bitunix-scanner-bot
    runtime: node
    plan: starter
    region: singapore
    buildCommand: curl https://s3.amazonaws.com/quotaguard/qgtunnel-latest.tar.gz | tar xz && npm install
    startCommand: bin/qgtunnel node bot.js
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: INTERVAL_MIN
        value: "10"
      - key: QUOTAGUARDSTATIC_URL
        sync: false
      - key: QGTUNNEL_DEBUG
        value: "true"
